---
version: '3'
services:
  api:
    build:
      context: ./api
      dockerfile: FastApiDockerfile
    ports:
      - "80:80"
    volumes:
      - models:/models    
    environment:
      - DATABASE_URL=postgresql://fastapi:fastapi@postgres:5432/movies
    depends_on:
      - postgres
      - model
    links:
      - postgres:postgres
  postgres:
    image: postgres:14.5-alpine
    restart: always
    environment:
      POSTGRES_USER: fastapi
      POSTGRES_PASSWORD: fastapi
      POSTGRES_DB: fastapi
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
  streamlit:
    build:
      context:  ./streamlit
      dockerfile: Dockerfile
    volumes:
      - .:/app
    environment:
      - API_URL=http://api:80
      - BASE_URL=http://localhost:8501
    ports:
      - 8501:8501
    depends_on:
      - postgres
  model:
    build:
      context: ./model
      dockerfile: Dockerfile
    volumes:
      - models:/model/models
      - mlruns:/tmp
    ports:
      - 5000:5000

volumes:
  postgres:
  mlruns:
  models: