CREATE DATABASE movies;
GRANT ALL PRIVILEGES ON DATABASE movies TO fastapi;
\c movies;
SET search_path = public;
CREATE TABLE TEST(ID NUMERIC, DESCRIPTION TEXT);
INSERT INTO TEST VALUES (1, 'Hello');